# Generated by Django 2.1 on 2019-02-22 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word_cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='words',
            old_name='user',
            new_name='author',
        ),
    ]
