# Generated by Django 2.1 on 2018-12-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ua_word', models.CharField(max_length=200)),
                ('en_word', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
