# Generated by Django 2.1 on 2019-01-02 10:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('word_cards', '0002_auto_20181217_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='added_data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='words',
            name='en_word',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='words',
            name='ua_word',
            field=models.CharField(max_length=12),
        ),
    ]
