# Generated by Django 2.1 on 2019-02-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_cards', '0002_auto_20190222_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='en_word',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='words',
            name='ua_word',
            field=models.CharField(max_length=30),
        ),
    ]
