# Generated by Django 2.1 on 2019-01-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_cards', '0003_auto_20190102_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='added_data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
