# Generated by Django 2.1 on 2019-01-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_cards', '0004_auto_20190102_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='words',
            name='ua_word',
        ),
        migrations.AddField(
            model_name='words',
            name='ua_word_first',
            field=models.CharField(default=2, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='words',
            name='ua_word_second',
            field=models.CharField(default=None, max_length=16),
        ),
        migrations.AddField(
            model_name='words',
            name='ua_word_third',
            field=models.CharField(default=None, max_length=16),
        ),
        migrations.AlterField(
            model_name='words',
            name='en_word',
            field=models.CharField(max_length=16),
        ),
    ]
