# Generated by Django 2.1 on 2019-01-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_cards', '0005_auto_20190117_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='ua_word_second',
            field=models.CharField(max_length=16, null='2'),
        ),
        migrations.AlterField(
            model_name='words',
            name='ua_word_third',
            field=models.CharField(max_length=16, null='3'),
        ),
    ]
