# Generated by Django 2.1 on 2019-01-17 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word_cards', '0006_auto_20190117_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='words',
            old_name='ua_word_first',
            new_name='ua_word',
        ),
        migrations.RemoveField(
            model_name='words',
            name='ua_word_second',
        ),
        migrations.RemoveField(
            model_name='words',
            name='ua_word_third',
        ),
    ]
